name: order_support
description: 楽膳向け 発注をサポートするアプリ

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true